books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path( 'add_books/', views.add_books, name='add_books'),
    path('book/<int:id>', views.book, name='book'),
]

flashcard/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('new_flashcard/', views.new_flashcard, name='new_flashcard'),
    path('delete_flashcard/<int:id>', views.delete_flashcard, name='delete_flashcard'),
    path('start_challenge/', views.start_challenge, name='start_challenge'),
    path('list_challenge/', views.list_challenge, name='list_challenge'),
    path('challenge/<int:id>/', views.challenge, name='challenge'),
    path('toRespond_flashcard/<int:id>/', views.toRespond_flashcard, name="toRespond_flashcard"),
    path('report/<int:id>/', views.report, name='report'),
]

study_async/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('flashcard/', include('flashcard.urls')),
    path('books/', include('books.urls')),
    path('', lambda requests: redirect('/flashcard/new_flashcard')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

flashcard/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.safestring import mark_safe

class Category(models.Model):
    name = models.CharField(max_length = 20)

    def __str__(self):
        return self.name
    
class Flashcard(models.Model):
    DIFFICULTY_CHOICES = (('H', 'Hard'), ('M', 'Medium '), ('E', 'Easy'))
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    question = models.CharField(max_length=100)
    answer = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    difficulty = models.CharField(max_length=1, choices=DIFFICULTY_CHOICES)
    
    def __str__(self):
        return self.question
    
    @property
    def css_difficulty(self):
        if self.difficulty == 'E':
            return 'flashcard-easy'
        elif self.difficulty == 'M':
            return 'flashcard-medium'
        elif self.difficulty == 'H':
            return 'flashcard-hard'
    
class FlashcardChallenge(models.Model):
    flashcard = models.ForeignKey(Flashcard, on_delete=models.DO_NOTHING)
    answered = models.BooleanField(default=False)
    gotItRight = models.BooleanField(default=False)

    def __str__(self):
        return self.flashcard.question
    
class Challenge(models.Model):
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=100)
    category = models.ManyToManyField(Category)
    quantity_questions = models.IntegerField()
    difficulty = models.CharField(
        max_length=1, choices=Flashcard.DIFFICULTY_CHOICES
    )
    flashcards = models.ManyToManyField(FlashcardChallenge)

    def __str__(self):
        return self.title
    
    def status(self):
        if self.flashcards.filter(answered = False).exists():
            return mark_safe('<span class="badge bg-primary">Em aberto</span>')
        else:
            return mark_safe('<span class="badge bg-success">Concluído</span>')

flashcard/views.py
from django.shortcuts import render, redirect
from .models import Category, Flashcard, Challenge, FlashcardChallenge
from django.http import HttpResponse, Http404
from django.contrib.messages import constants
from django.contrib import messages

def new_flashcard(request):
    if not request.user.is_authenticated:
        return redirect('/users/login')
    
    if request.method == "GET":
        categories = Category.objects.all()
        difficulties = Flashcard.DIFFICULTY_CHOICES
        flashcards = Flashcard.objects.filter(user = request.user)
        category_filter = request.GET.get('category')
        difficulty_filter = request.GET.get('difficulty')

        if (category_filter):
            flashcards = flashcards.filter(category__id = category_filter)

        if (difficulty_filter):
            flashcards = flashcards.filter(difficulty = difficulty_filter)

        return render(request, 'new_flashcard.html', {'categories': categories, 'difficulties': difficulties, 'flashcards': flashcards})

    elif request.method == 'POST':
        question = request.POST.get('question')
        answer = request.POST.get('answer')
        category = request.POST.get('category')
        difficulty = request.POST.get('difficulty')

        if len(question.strip()) == 0 or len(answer.strip()) == 0:
            messages.add_message(request, constants.ERROR, "Fill in the question and answer fields")
            return redirect('/flashcard/new_flashcard/')

        flashcard = Flashcard(
            user = request.user,
            question = question,
            answer = answer,
            category_id = category,
            difficulty = difficulty
        )

        flashcard.save()

        messages.add_message(request, constants.SUCCESS, "Flashcard successfully registered")
        return redirect ('/flashcard/new_flashcard')

def delete_flashcard(request, id):
    
    flashcard = Flashcard.objects.get(id = id)
    flashcard.delete()
    messages.add_message(request, constants.SUCCESS, "Flashcard successfully deleted!")
    return redirect('/flashcard/new_flashcard/')

def start_challenge(request):
    if request.method == "GET":
        categories = Category.objects.all()
        difficulties = Flashcard.DIFFICULTY_CHOICES
        return render(request, 'start_challenge.html',{'categories': categories, 'difficulties': difficulties})
    elif request.method == "POST":
        title = request.POST.get('title')
        category = request.POST.getlist('category')
        difficulty = request.POST.get('difficulty')
        qnt_questions = request.POST.get('qnt_questions')

        challenge = Challenge(
            user = request.user,
            title = title,
            quantity_questions = qnt_questions,
            difficulty = difficulty,
        )

        challenge.save()

        # são equivalentes:
        challenge.category.add(*category) # "for inline"

        # for category in categories:         # for "normal"
        #     challenge.category.add(category)

        flashcards = (
            Flashcard.objects.filter(user = request.user)
            .filter(difficulty = difficulty)
            .filter(category_id__in = category)
            .order_by('?') # id (id de forma crescente) / -id(id de forma descrescente) - ?(traz os dados de forma aleatória)
        )

        if flashcards.count() < int(qnt_questions):

            messages.add_message(request, constants.ERROR,(f"You requested {qnt_questions} flashcard. However, there are only {flashcards.count()} flashcards registrations.!"))
            return redirect ('/flashcard/start_challenge/')

        flashcards = flashcards[: int(qnt_questions)]

        for f in flashcards:
            flashcard_challenge =  FlashcardChallenge(
                flashcard = f
            )
            flashcard_challenge.save()
            challenge.flashcards.add(flashcard_challenge)

        challenge.save()

        return redirect('/flashcard/list_challenge')

def list_challenge(request):
    challenge = Challenge.objects.filter(user=request.user)

    categories = Category.objects.all()
    difficulties = Flashcard.DIFFICULTY_CHOICES

    category = request.GET.get('category')
    difficulty = request.GET.get('difficulty')

    if category:
        challenge = challenge.filter(category__id=category)
    if difficulty:
        challenge = challenge.filter(difficulty=difficulty)

    return render(request, 'list_challenge.html', {'challenges': challenge, 'categories': categories, 'difficulties':difficulties})

def challenge(request, id):
    challenge = Challenge.objects.get(id=id)
    
    if not challenge.user == request.user:
        raise Http404()
    
    if request.method == "GET":
        hits = challenge.flashcards.filter(answered = True).filter(gotItRight = True).count()
        errors = challenge.flashcards.filter(answered = True).filter(gotItRight = False).count()
        missing = challenge.flashcards.filter(answered = False).count()
        return render (request, 'challenge.html', {'challenge':challenge, 'hits':hits, 'errors':errors, 'missing':missing})
    
    return HttpResponse(id)

def toRespond_flashcard(request, id):

    flashcard_challenge = FlashcardChallenge.objects.get(id=id)
    right = request.GET.get('right')
    challenge_id = request.GET.get('challenge_id')

    if not flashcard_challenge.flashcard.user == request.user:
        raise Http404()


    flashcard_challenge.answered = True

    flashcard_challenge.gotItRight = True if right == '1' else False
    flashcard_challenge.save()

    return redirect(f'/flashcard/challenge/{challenge_id}')

def report(request, id):
    challenge = Challenge.objects.get(id=id)

    hits = challenge.flashcards.filter(gotItRight = True).count()
    errors = challenge.flashcards.filter(gotItRight = False).count()

    datas = [hits,errors]

    categories = challenge.category.all()

    name_category = [i.name for i in categories]

    data2 = []

    for category in categories:
        data2.append(challenge.flashcards.filter(flashcard__category = category).filter(gotItRight=True).count())

    print(name_category)
    print(data2)

    return render(request, 'report.html', {'challenge':challenge, 'datas': datas, 'name_category':name_category, 'data2':data2})

flashcard/templates/challenge.html
{% extends "base.html" %} {% load static %} {% block 'header' %}
<link href="{% static 'users/css/register.css' %}" rel="stylesheet" />
<link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet" />
<link
  href="{% static 'flashcard/css/start_challenge.css' %}"
  rel="stylesheet"
/>
<link href="{% static 'flashcard/css/challenge.css' %}" rel="stylesheet" />
<link
  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
  rel="stylesheet"
/>
{% endblock 'header' %} {% block 'content' %}
{% include 'partials/header.html'%}
<div class="container">
  <br />
  <br />
  <div class="row">
    <div class="col-md">
      <h3 class="font-second">Challenge Started</h3>
      <span class="badge-category">Programming</span>
      <span class="badge-category">Math</span>
      <br />
      <br />
      <br />
      {% for flash in challenge.flashcards.all %}
      <div class="box-new-flashcard {% if flash.answered %} op2 {% endif %}">
        <div class="flashcard {{flash.flashcard.css_difficulty}}">
          <div class="flashcard-category">{{flash.flashcard.category}}</div>
          <br />
          <br />
          <div class="flashcard-box-item" onclick="flip_card({{flash.id}})">
            <p class="flashcard-item">{{flash.flashcard.question}}</p>
          </div>
          {% if not flash.answered %}
          <div class="toRespond">
            <a href="{% url 'toRespond_flashcard' flash.id %}?right=0&challenge_id={{challenge.id}}"><i class="bx bxs-x-square icone-red"></i></a>
            <a href="{% url 'toRespond_flashcard' flash.id %}?right=1&challenge_id={{challenge.id}}"><i class="bx bxs-check-square icone-green"></i></a>
          </div>
          {% else %}
            {% if flash.gotItRight %}
                <span class="badge bg-success">Right</span>
            {% else %}
                <span class="badge bg-danger">Missed</span>
            {% endif %}
         {% endif %}
        </div>
        <div class="answer-flashcard" id="{{flash.id}}">
          {{flash.flashcard.answer}}
        </div>
      </div>
      <br />
      <br />
      {% endfor %}
    </div>
    <div class="col-md">
      <h3 class="font-second">Results</h3>
      <p class="font-p">Hits: {{hits}}</p>
      <p class="font-p">Errors: {{errors}}</p>
      <p class="font-p">Missing: {{missing}}</p>
      <br />
      <a class="btn-register btn-challenge" href="{% url 'report' challenge.id%}">Detailed Report</a>
    </div>
  </div>
</div>
<script src="{% static 'flashcard/js/flashcard.js' %}"></script>
{% endblock 'content' %}

flashcard/templates/list_challenge.html
{% extends "base.html" %}
{% load static %}
{% block 'header' %}
<link href="{% static 'users/css/register.css' %}" rel="stylesheet">
<link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
<link href="{% static 'flashcard/css/start_challenge.css' %}" rel="stylesheet">
<link href="{% static 'flashcard/css/challenge.css' %}" rel="stylesheet">
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
{% endblock 'header' %}
{% block 'content' %}
{% include 'partials/header.html'%}
<div class="container">
<br>
<br>
<div class="row">
<div class="col-md">
<form action="{% url 'list_challenge' %}" method="GET">
<label for="">Category</label>
<select name="category" class="form-select">
    <option value=""></option>
    {% for category in categories %}
        <option value="{{category.id}}">{{category}}</option>
    {% endfor%}
</select>
</div>
<div class="col-md">
<label for="">Difficulty</label>
<select name="difficulty" class="form-select">
    <option value=""></option>
    {% for difficulty in difficulties%}
    <option value="{{difficulty.0}}">{{difficulty.1}}</option>
    {% endfor%}
</select>
</div>
<div class="col-md">
<br>
<input type="submit" value="Filter" class="btn-register">
</form>
</div>
</div>
<br>
<br>
<div class="box-list">
<table>
<thead>
<tr>
<th scope="col">Challenge</th>
<th scope="col">Title</th>
<th scope="col">Level</th>
<th scope="col">Status</th>
</tr>
</thead>
<tbody>
{% for challenge in challenges%}
<tr class="line">
<th><a href="{% url 'challenge' challenge.id %}">{{challenge.id}}</a></th>
<td>{{challenge.title}}</td>
<td>{{challenge.get_difficulty_display}}</td>
<td>{{challenge.status}}</td>
</tr>
{% endfor %}
</tbody>
</table>
</div>
</div>
<script src="{% static 'flashcard/js/flashcard.js' %}"></script>
{% endblock 'content' %}

flashcard/templates/new_flashcard.html
<!-- @format -->

{% extends "base.html" %} {% load static %} {% block 'header' %}
<link href="{% static 'users/css/register.css' %}" rel="stylesheet" />
<link
  href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css"
  rel="stylesheet" />
<link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet" />
{% endblock 'header' %}
{% block 'content' %}
{% include 'partials/header.html'%}
<div class="container">
  <br />
  <br />
  <div class="row">
    <div class="col-md">
      <div class="box-form">
        <form action="{% url 'new_flashcard' %}" method="POST">
          {% csrf_token %} {% csrf_token %}
          <h3>New flashcard</h3>
          {% if messages %}
          <br />
          {% for message in messages %}
          <section class="alert {{message.tags}}">{{message}}</section>
          {% endfor %} {% endif %}
          <br />
          <label>Question</label>
          <input
            type="text"
            class="form-control"
            placeholder="Question"
            name="question" />
          <br />
          <label>Answer</label>
          <textarea class="form-control" name="answer"></textarea>
          <br />
          <div class="row">
            <div class="col-md">
              <label for="">Category</label>
              <select class="form-select" name="category">
                {% for category in categories %}
                <option value="{{category.id}}">{{ category }}</option>
                {% endfor %}
              </select>
            </div>
            <div class="col-md">
              <label for="">Difficulty</label>
              <select class="form-select" name="difficulty">
                {% for difficulty in difficulties %}
                <option value="{{difficulty.0}}">{{ difficulty.1 }}</option>
                {% endfor %}
              </select>
            </div>
          </div>
          <br />
          <input type="submit" value="Send" class="btn-register" />
          <br />
          <br />
          <br />
        </form>
      </div>
    </div>
    <div class="col-md">
      <form action="{% url 'new_flashcard' %}" method="GET">
        <div class="row">
          <div class="col-md">
            <label for="">Category</label>
            <select name="category" id="" class="form-select">
              <option value="">All Categories</option>
              {% for category in categories %}
              <option value="{{category.id}}">{{ category }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md">
            <label for="">Difficulty</label>
            <select name="difficulty" id="" class="form-select">
              <option value="">All Difficulties</option>
              {% for difficulty in difficulties %}
              <option value="{{difficulty.0}}">{{ difficulty.1 }}</option>
              {% endfor %}
            </select>
          </div>
          <div class="col-md">
            <br />
            <input
              type="submit"
              style="width: 100%"
              value="Filter"
              class="btn-register" />
          </div>
        </div>
      </form>
      <br />
      <br />
      {% for flashcard in flashcards %}
      <div class="box-new-flashcard">
        <div class="flashcard {{flashcard.css_difficulty}}">
          <div class="flashcard-category">{{flashcard.category}}</div>
          <a href="{% url 'delete_flashcard' flashcard.id%}"><i class="icone-exit bx bx-x-circle"></i></a>
          <br />
          <br />
          <div class="flashcard-box-item" onclick="flip_card({{flashcard.id}})">
            <p class="flashcard-item">{{flashcard.question}} ?</p>
          </div>
        </div>
        <div class="answer-flashcard" id="{{flashcard.id}}">
          {{flashcard.answer}}
        </div>
      </div>
      <br />
      <br />
      {% endfor %}
    </div>
  </div>
</div>
<script src="{% static "flashcard/js/flashcard.js" %}"></script>
{% endblock 'content' %}

flashcard/templates/report.html
{% extends "base.html" %}
{% load static %}

{% block 'header' %}

    <link href="{% static 'users/css/register.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/start_challenge.css' %}" rel="stylesheet">
    <link href="{% static 'flashcard/css/challenge.css' %}" rel="stylesheet">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

{% endblock 'header' %}


{% block 'content' %}
    {% include "partials/header.html" %}
    <div class="container">
        <br>
        <br>
        <div class="row">
            <div class="col-md">
                <p class="font-second">{{challenge.title}}</p>
                <hr>
                <canvas id="graphic1"></canvas>
            </div>
            <div class="col-md">
                <br><br><br><br>
                
                <div style="background-color: white;">

                    <canvas id="graphic2"></canvas>

                </div>
            </div>
        </div>

    </div>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        const ctx = document.getElementById('graphic1');
      
        new Chart(ctx, {
          type: 'pie',
          data: {
            labels: ['Hits', 'Errors'],
            datasets: [{
              label: 'Qnt',
              data: {{datas}},
              borderWidth: 0
            }]
          },
          
        });
    </script>

    <script>

        const ctx2 = document.getElementById('graphic2');
      
        new Chart(ctx2, {
          type: 'radar',
          data: {
            labels: {{name_category|safe}},
            datasets: [{
              label: 'Qnt',
              data: {{data2}},
              borderWidth: 1,
              fill: true,
              backgroundColor: 'rgba(255, 99, 132, 0.2)',
              borderColor: 'rgb(255, 99, 132)',
              pointBackgroundColor: 'rgb(255, 99, 132)',
              pointBorderColor: '#fff',
              pointHoverBackgroundColor: '#fff',
              pointHoverBorderColor: 'rgb(255, 99, 132)'
            }]
          },
          
        });

    </script>
{% endblock 'content' %}

flashcard/templates/start_challenge.html
{% extends "base.html" %}
{% load static %}
{% block 'header' %}
<link href="{% static 'users/css/register.css' %}" rel="stylesheet">
<link href="{% static 'flashcard/css/new_flashcard.css' %}" rel="stylesheet">
<link href="{% static 'flashcard/css/start_challenge.css' %}" rel="stylesheet">
{% endblock 'header' %}
{% block 'content' %}
{% include 'partials/header.html'%}
<div class="container ctx">
<br>
<br>
<h2 class="font-first">Start Challenge</h2>
<p class="font-second">Choose the categories and difficulty of the challenge</p>
{% if messages %}
          <br />
          {% for message in messages %}
          <section class="alert {{message.tags}}">{{message}}</section>
          {% endfor %} {% endif %}
<div class="row">
        <div class="col-md">
            <form action="{% url 'start_challenge' %}" method="POST">{% csrf_token %}
            <label for="">Title</label>
            <input type="text" class="form-control" name="title">
        </div>
<div class="col-md">
<label>Category</label>
<select name="category" class="form-select" multiple>
{% for category in categories %}
<option value="{{category.id}}">
{{category.name}}
</option>
{% endfor %}
</select>
</div>
<div class="col-md">
<label>Difficulty</label>
<select name="difficulty" class="form-select">
{% for difficulty in difficulties %}
<option value="{{difficulty.0}}">
{{difficulty.1}}
</option>
{% endfor %}
</select>
</div>
<div class="col-md">
<label>Quantity Questions</label>
<input type="number" class="form-control" name="qnt_questions">
</div>
</div>
<br>
<br>
<input type="submit" class="btn-register" value="Start Challenge">
</form>
</div>
{% endblock 'content' %}